services:
  chatgpt-tarot-divination:
    # image: ghcr.io/dreamhunter2333/chatgpt-tarot-divination:latest
    build: .
    container_name: chatgpt-tarot-divination
    restart: always
    ports:
      - 8000:8000
    environment:
      - api_key=sk-2acae0c3bd934dc0bbfbe40fc1f22277
      - api_base=https://dashscope.aliyuncs.com/compatible-mode/v1
      - model=qwen-plus
      # - rate_limit=10/minute # optional
      # - user_rate_limit=600/hour # optional
      - github_client_id=xxx
      - github_client_secret=xxx
      - jwt_secret=secret
      - ad_client=ca-pub-xxx
      - ad_slot=123
